---
- name: NGINX | Install epel-release
  become: true
  ansible.builtin.yum:
    name: epel-release
    state: present
- name: Nginx | Install Nginx
  become: true
  ansible.builtin.yum:
    name: nginx
    state: present
- name: Nginx | Create config
  become: true
  ansible.builtin.template:
    src: "./template/nginx.yml.j2"
    dest: "/etc/nginx/nginx.conf"
    mode: '0644'
  notify: start-nginx

- name: Lighthouse | Install Dependencies
  become: true
  ansible.builtin.yum:
    name: git
    state: present
- name: Create Lighthouse directory
  become: true
  ansible.builtin.file:
    path: /var/www/lighthouse
    state: directory
    recurse: true
    mode: '0755'
    owner: nginx
    group: nginx
- name: Lighthouse | Clone from Git
  become: true
  ansible.builtin.git:
    repo: "{{ lighthouse_vcs }}"
    version: master
    dest: "{{ lighthouse_location_dir }}"
    force: true
- name: Lighthouse | Create lighthouse config
  become: true
  ansible.builtin.template:
    src: "./template/lighthouse.yml.j2"
    dest: "/etc/nginx/conf.d/default.conf"
    mode: '0644'
  notify: reload-nginx